# Generated by Django 5.2.6 on 2025-09-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests_origin', to='destinations.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests_destination', to='destinations.destination'),
        ),
        migrations.CreateModel(
            name='FlightAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avail_destination_set', to='destinations.destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avail_origin_set', to='destinations.destination')),
            ],
            options={
                'ordering': ['date', 'origin__name', 'destination__name'],
                'unique_together': {('origin', 'destination', 'date')},
            },
        ),
    ]
